### ISSUE TITLE
Issues when run command freeswitch_exporter

### ISSUE THREAD

**Issue by adamspatrick2020** [znerol/prometheus-freeswitch-exporter#1]
I got this error when run command: 
freeswitch_exporter config=/root/esl.yml
Traceback (most recent call last):
  File "/usr/local/bin/freeswitch_exporter", line 7, in <module>
    from freeswitch_exporter.cli import main
  File "/usr/local/lib/python2.7/dist-packages/freeswitch_exporter/cli.py", line 7, in <module>
    from freeswitch_exporter.http import start_http_server
  File "/usr/local/lib/python2.7/dist-packages/freeswitch_exporter/http.py", line 59
    response = Response(f"Module '{module}' not found in config")
                                                               ^
SyntaxError: invalid syntax

Could you help me how to run command correctly. I'm new in python.
Thank you !

**Comment by znerol** [comment]
Hi, could you please post your `/root/esl.yml` (without the password obviously).

**Comment by znerol** [comment]
Oh, wait. This is not a config issue. It seems you are using Python 2. `prometheus-freeswitch-exporter` is Python 3 only.

*Edit:* Depending on your distro you might have to type `pip3 install prometheus-freeswitch-exporter` (instead of `pip install` ...).

**Comment by adamspatrick2020** [comment]
With python3, has other error:
freeswitch_exporter /root/esl.yml
Traceback (most recent call last):
  File "/usr/local/bin/freeswitch_exporter", line 7, in <module>
    from freeswitch_exporter.cli import main
  File "/usr/local/lib/python3.6/dist-packages/freeswitch_exporter/cli.py", line 7, in <module>
    from freeswitch_exporter.http import start_http_server
  File "/usr/local/lib/python3.6/dist-packages/freeswitch_exporter/http.py", line 16, in <module>
    from freeswitch_exporter.collector import collect_esl
  File "/usr/local/lib/python3.6/dist-packages/freeswitch_exporter/collector.py", line 10, in <module>
    from contextlib import asynccontextmanager
ImportError: cannot import name 'asynccontextmanager'

I use default esl.yml file with my freeswitch password:
default:
    port: 8021  # default port, can be omitted
    password: <my password>

**Comment by adamspatrick2020** [comment]
It worked when i installed python 3.8 from source :)
Thank you for your support.
