### ISSUE TITLE
how to solve this issue response = Response(f"Module '{module}' not found in config")

### ISSUE THREAD

**Issue by herbiel** [znerol/prometheus-freeswitch-exporter#3]
freeswitch_exporter 
Traceback (most recent call last):
  File "/usr/local/bin/freeswitch_exporter", line 11, in <module>
    load_entry_point('prometheus-freeswitch-exporter==1.0.0', 'console_scripts', 'freeswitch_exporter')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/freeswitch_exporter/cli.py", line 7, in <module>
    from freeswitch_exporter.http import start_http_server
  File "/usr/local/lib/python2.7/dist-packages/freeswitch_exporter/http.py", line 59
    response = Response(f"Module '{module}' not found in config")
                                                               ^
SyntaxError: invalid syntax

**Comment by znerol** [comment]
Please use _Python 3_ to run freeswitch exporter. Depending on your distribution you need to use `pip3` instead of `pip`.
